Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 2
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	PlotMapping
	1

[Mon Apr 12 20:22:24 2021]
rule PlotMapping:
    input: data/gc-eu-scrape.csv
    output: figures/eu-num-geocache.png, figures/eu-num-geocache-year.png, figures/eu-max-visits-date.png, figures/eu-eu-travellers.gif
    jobid: 0

[Mon Apr 12 20:22:33 2021]
Error in rule PlotMapping:
    jobid: 0
    output: figures/eu-num-geocache.png, figures/eu-num-geocache-year.png, figures/eu-max-visits-date.png, figures/eu-eu-travellers.gif

RuleException:
CalledProcessError in line 48 of /home/adrian/PhD-Laptop/Pd_Geocache/workflow/eu_snakefile:
Command 'set -euo pipefail;  Rscript --vanilla /home/adrian/PhD-Laptop/Pd_Geocache/workflow/.snakemake/scripts/tmppiluw4z3.eu_geocache_mapping.R' returned non-zero exit status 1.
  File "/home/adrian/anaconda3/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2189, in run_wrapper
  File "/home/adrian/PhD-Laptop/Pd_Geocache/workflow/eu_snakefile", line 48, in __rule_PlotMapping
  File "/home/adrian/anaconda3/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/home/adrian/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/home/adrian/anaconda3/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/adrian/anaconda3/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2201, in run_wrapper
Removing output files of failed job PlotMapping since they might be corrupted:
figures/eu-num-geocache.png, figures/eu-num-geocache-year.png
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/adrian/PhD-Laptop/Pd_Geocache/workflow/.snakemake/log/2021-04-12T202224.894525.snakemake.log
